---

name: "Bug Report"
about: " Report a reproducible bug or regression."
title: "Bug: "
status: "Bug"

---

<--
  Please provide a clear and concise description of what the bug is. Include
  screenshots if needed.
-->

## Steps To Reproduce

1.
2.

<--
  Issues without reproduction steps or
  code examples may be immediately closed as not actionable.
-->

Link to code example:

## The current behavior

## The expected behavior
